# syntax=docker/dockerfile:1

ARG RUBY_VERSION=3.3.6
FROM ruby:${RUBY_VERSION}-slim AS base

WORKDIR /rails

RUN apt-get update -qq && \
  apt-get install --no-install-recommends -y \
  curl \
  libjemalloc2 \
  libvips \
  postgresql-client \
  && rm -rf /var/lib/apt/lists /var/cache/apt/archives

RUN gem install foreman

ENV RAILS_ENV="development" \
  BUNDLE_PATH="/usr/local/bundle" \
  BUNDLE_JOBS=4 \
  BUNDLE_RETRY=3

FROM base AS build

RUN apt-get update -qq && \
  apt-get install --no-install-recommends -y \
  build-essential \
  git \
  libpq-dev \
  node-gyp \
  pkg-config \
  python-is-python3 \
  gnupg \
  && rm -rf /var/lib/apt/lists /var/cache/apt/archives

ARG NODE_MAJOR=20
ARG YARN_VERSION=1.22.22
RUN curl -fsSL "https://deb.nodesource.com/setup_${NODE_MAJOR}.x" | bash - && \
  apt-get install --no-install-recommends -y nodejs && \
  npm install -g yarn@${YARN_VERSION} && \
  rm -rf /var/lib/apt/lists /var/cache/apt/archives

COPY Gemfile Gemfile.lock ./
RUN bundle config unset without && \
  bundle install && \
  rm -rf ~/.bundle/ \
  "${BUNDLE_PATH}"/ruby/*/cache \
  "${BUNDLE_PATH}"/ruby/*/bundler/gems/*/.git && \
  bundle exec bootsnap precompile --gemfile

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .

RUN bundle exec bootsnap precompile app/ lib/

FROM base

COPY --from=build "${BUNDLE_PATH}" "${BUNDLE_PATH}"
COPY --from=build /rails /rails

RUN groupadd --system --gid 1000 rails && \
  useradd rails --uid 1000 --gid 1000 --create-home --shell /bin/bash && \
  chown -R rails:rails db log storage tmp
USER 1000:1000

ENTRYPOINT ["/rails/bin/docker-entrypoint"]

EXPOSE 3000

CMD ["./bin/dev"]
