services:
  db:
    image: postgres:15.0-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: uber_challenge_${RAILS_ENV}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - "5432:5432"

volumes:
  db-data:
